"""Acceptance tests for T-09: render `ts-review.md` / `ts-review.json` from a
`Review`, and write both atomically.

Golden files under `tests/fixtures/expected/` are hand-authored against the template
documented in `render.py`'s module docstring, not generated by running the renderer
and pasting its output -- a golden that copies the code proves nothing. `Review`
fixtures are built directly from `compose.Finding` / `compose.Review` /
`checks.CheckResult`, the same way `tests/test_compose.py` does, so this file never
calls the model or `compose()` itself.
"""

from __future__ import annotations

import json
import os
from dataclasses import replace
from pathlib import Path

import pytest

from typesafe_review.ask import AskResult
from typesafe_review.checks import CheckResult
from typesafe_review.compose import UNANSWERED, Finding, Review
from typesafe_review.questions import Severity
from typesafe_review.render import OUTPUT_JSON, OUTPUT_MD, RenderError, render_json, render_markdown, write_outputs
from typesafe_review.verdict import Verdict

FIXTURES = Path(__file__).parent / 'fixtures' / 'expected'


def _finding(
    *,
    severity: Severity,
    file: str | None,
    symbol: str,
    issue: str,
    why: str,
    fix: str,
    question_id: str,
    probability: float | None,
    confidence: float | None = None,
    reason: str | None = None,
) -> Finding:
    return Finding(
        severity=severity,
        file=file,
        symbol_or_area=symbol,
        issue=issue,
        why_it_matters=why,
        concrete_fix=fix,
        blocks_merge=severity in ('blocker', 'important'),
        question_id=question_id,
        probability=probability,
        confidence=confidence,
        reason=reason,
    )


def _counts(findings: list[Finding]) -> dict[str, int]:
    counts = {'blocker': 0, 'important': 0, 'minor': 0, 'nit': 0}
    for f in findings:
        counts[f.severity] += 1
    return counts


# --- scenario 1: APPROVE, everything empty ---------------------------------------


def _approve_review() -> Review:
    checks = [
        CheckResult(name='red proof', status='pass', notes='3 acceptance tests fail at a1b2c3d, ImportError'),
        CheckResult(name='green at HEAD', status='pass', notes='same 3 pass; tests/ unchanged since a1b2c3d'),
        CheckResult(name='make check', status='pass', notes='exit 0'),
    ]
    return Review(
        verdict=Verdict.APPROVE,
        score=5,
        summary='No blocking issues found; ready to merge.',
        findings=[],
        uncertain=[],
        counts=_counts([]),
        stop_reason='approved',
        required_checks=checks,
    )


# --- scenario 2: CHANGES_REQUESTED, all four severities, one file=None -----------


def _changes_requested_review() -> Review:
    findings = [
        _finding(
            severity='blocker',
            file=None,
            symbol='<change>',
            issue='The change reports success on a path it never verified.',
            why='A caller cannot tell a real success from an unverified one.',
            fix='Check the condition before returning success.',
            question_id='success_on_unverified',
            probability=0.82,
        ),
        _finding(
            severity='important',
            file='src/example/config.py',
            symbol='resolve_bind_address',
            issue='The change duplicates existing behavior instead of using the shared helper.',
            why='The duplicated path can drift and create inconsistent results.',
            fix='Route the new call through the existing helper and extend it if needed.',
            question_id='duplicates_helper',
            probability=0.91,
        ),
        _finding(
            severity='minor',
            file='src/example/config.py',
            symbol='resolve_bind_address',
            issue='An unexplained literal gates behaviour.',
            why='A future reader cannot tell why this value was chosen.',
            fix='Name the constant and explain the choice.',
            question_id='magic_constant',
            probability=0.78,
        ),
        _finding(
            severity='nit',
            file='src/example/config.py',
            symbol='resolve_bind_address',
            issue='Uses `os.path` where `pathlib.Path` is the local convention.',
            why='Inconsistent path handling adds friction when reading nearby code.',
            fix='Switch to `pathlib.Path`.',
            question_id='os_path_over_pathlib',
            probability=0.76,
        ),
    ]
    checks = [
        CheckResult(name='red proof', status='pass', notes='2 acceptance tests fail at f00dcafe'),
        CheckResult(name='green at HEAD', status='pass', notes='same 2 pass'),
        CheckResult(name='make check', status='fail', notes='ruff: 1 error in src/example/config.py'),
    ]
    return Review(
        verdict=Verdict.CHANGES_REQUESTED,
        score=2,
        summary='1 blocker(s) and 1 important finding(s) must be resolved before merge.',
        findings=findings,
        uncertain=[],
        counts=_counts(findings),
        stop_reason='changes_requested',
        required_checks=checks,
    )


# --- scenario 3: NEEDS_HUMAN, with uncertain entries ------------------------------


def _needs_human_review() -> Review:
    uncertain = [
        _finding(
            severity='important',
            file='src/example/pipeline.py',
            symbol='<change>',
            issue='Score-based `mixed_responsibility` fired but confidence was below the gate.',
            why='Low-confidence model answers are listed for the orchestrator, not acted on.',
            fix='A human should look at `pipeline.py` directly.',
            question_id='mixed_responsibility',
            probability=0.6,
            confidence=0.42,
        ),
        _finding(
            severity='blocker',
            file=None,
            symbol='<change>',
            issue='Whether the change satisfies "reject malformed input" could not be told confidently.',
            why='A grey-zone criterion answer is a planning question, not a fix.',
            fix='A human should confirm whether this criterion is met.',
            question_id='criterion_1_satisfied',
            probability=0.55,
        ),
        _finding(
            severity='important',
            file='src/example/pipeline.py',
            symbol='validate',
            issue='Expected an answer for `duplicates_helper` but the response never included one.',
            why='An unanswered question cannot be scored either way.',
            fix='Re-run the review; if this persists, check the request payload.',
            question_id='duplicates_helper',
            probability=None,
            reason=UNANSWERED,
        ),
    ]
    checks = [
        CheckResult(name='red proof', status='pass', notes='1 acceptance test fails at deadbeef'),
        CheckResult(name='green at HEAD', status='pass', notes='same test passes'),
        CheckResult(name='make check', status='pass', notes='exit 0'),
    ]
    return Review(
        verdict=Verdict.NEEDS_HUMAN,
        score=1,
        summary='Human judgement is needed before this can proceed.',
        findings=[],
        uncertain=uncertain,
        counts=_counts([]),
        stop_reason='needs_human',
        required_checks=checks,
    )


SCENARIOS = {
    'approve': _approve_review,
    'changes_requested': _changes_requested_review,
    'needs_human': _needs_human_review,
}


def _engine() -> AskResult:
    return AskResult(answers={}, requests=7, input_tokens=41200, model='jev-latest')


@pytest.mark.parametrize('name', sorted(SCENARIOS))
def test_render_markdown_matches_golden(name: str) -> None:
    review = SCENARIOS[name]()
    actual = render_markdown(review)
    expected = (FIXTURES / f'{name}.md').read_text()
    assert actual == expected


@pytest.mark.parametrize('name', sorted(SCENARIOS))
def test_written_outputs_match_golden_byte_for_byte(name: str, tmp_path: Path) -> None:
    """The bytes actually written to the worktree -- not just the in-memory dict --
    match the hand-authored golden files exactly, markdown and JSON alike.
    """
    review = SCENARIOS[name]()
    md = render_markdown(review)
    json_obj = render_json(
        review, _engine(), Path('/app/.claude/worktrees/T-09-render'), 'develop', ['note one', 'note two']
    )
    write_outputs(tmp_path, md, json_obj)

    assert (tmp_path / OUTPUT_MD).read_text() == (FIXTURES / f'{name}.md').read_text()
    assert (tmp_path / OUTPUT_JSON).read_text() == (FIXTURES / f'{name}.json').read_text()


@pytest.mark.parametrize('name', sorted(SCENARIOS))
def test_render_json_round_trips_through_json_loads(name: str) -> None:
    review = SCENARIOS[name]()
    engine = AskResult(answers={}, requests=1, input_tokens=100, model='jev-latest')
    actual = render_json(review, engine, Path('/tmp/wt'), 'develop', [])
    round_tripped = json.loads(json.dumps(actual))
    assert round_tripped == actual


def test_golden_json_files_are_valid_json_with_expected_top_level_keys() -> None:
    for name in SCENARIOS:
        data = json.loads((FIXTURES / f'{name}.json').read_text())
        for key in (
            'verdict',
            'score',
            'summary',
            'worktree',
            'base',
            'required_checks',
            'findings',
            'uncertain',
            'counts',
            'stop_reason',
            'engine',
            'notes',
        ):
            assert key in data, f'{name}.json missing {key!r}'


# --- write_outputs: atomicity ------------------------------------------------------


def _write_inputs(tmp_path: Path) -> tuple[str, dict]:
    review = _approve_review()
    engine = AskResult(answers={}, requests=1, input_tokens=10, model='jev-latest')
    md = render_markdown(review)
    json_obj = render_json(review, engine, tmp_path, 'develop', [])
    return md, json_obj


def test_write_outputs_writes_both_files(tmp_path: Path) -> None:
    md, json_obj = _write_inputs(tmp_path)
    write_outputs(tmp_path, md, json_obj)
    assert (tmp_path / OUTPUT_MD).read_text() == md
    assert json.loads((tmp_path / OUTPUT_JSON).read_text()) == json_obj
    assert not (tmp_path / f'{OUTPUT_MD}.tmp').exists()
    assert not (tmp_path / f'{OUTPUT_JSON}.tmp').exists()


def test_write_outputs_failure_after_first_replace_leaves_no_files(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    md, json_obj = _write_inputs(tmp_path)

    real_replace = os.replace
    calls = {'n': 0}

    def flaky_replace(src, dst):  # type: ignore[no-untyped-def]
        calls['n'] += 1
        if calls['n'] == 1:
            return real_replace(src, dst)
        raise OSError('disk full')

    monkeypatch.setattr(os, 'replace', flaky_replace)

    with pytest.raises(RenderError) as exc_info:
        write_outputs(tmp_path, md, json_obj)

    assert isinstance(exc_info.value.__cause__, OSError)
    assert not (tmp_path / OUTPUT_MD).exists()
    assert not (tmp_path / OUTPUT_JSON).exists()
    assert not (tmp_path / f'{OUTPUT_MD}.tmp').exists()
    assert not (tmp_path / f'{OUTPUT_JSON}.tmp').exists()
    assert calls['n'] == 2


def test_write_outputs_counts_mismatch_raises_before_any_write(tmp_path: Path) -> None:
    md, json_obj = _write_inputs(tmp_path)
    json_obj['counts'] = {'blocker': 1, 'important': 0, 'minor': 0, 'nit': 0}

    with pytest.raises(RenderError):
        write_outputs(tmp_path, md, json_obj)

    assert not (tmp_path / OUTPUT_MD).exists()
    assert not (tmp_path / OUTPUT_JSON).exists()
    assert not (tmp_path / f'{OUTPUT_MD}.tmp').exists()
    assert not (tmp_path / f'{OUTPUT_JSON}.tmp').exists()
    assert list(tmp_path.iterdir()) == []


def test_write_outputs_cleanup_survives_a_failed_unlink(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Fix round 1, finding 1: a failing `unlink` during cleanup must not escape as
    a raw `OSError`, and must not stop the remaining cleanup targets from being
    attempted -- the original `RenderError` still propagates.
    """
    md, json_obj = _write_inputs(tmp_path)

    real_replace = os.replace
    replace_calls = {'n': 0}

    def flaky_replace(src, dst):  # type: ignore[no-untyped-def]
        replace_calls['n'] += 1
        if replace_calls['n'] == 1:
            return real_replace(src, dst)
        raise OSError('disk full')

    monkeypatch.setattr(os, 'replace', flaky_replace)

    real_unlink = Path.unlink
    unlink_attempts: list[Path] = []

    def flaky_unlink(self: Path, missing_ok: bool = False) -> None:
        unlink_attempts.append(self)
        if len(unlink_attempts) == 1:
            raise OSError('permission denied')
        real_unlink(self, missing_ok=missing_ok)

    monkeypatch.setattr(Path, 'unlink', flaky_unlink)

    with pytest.raises(RenderError) as exc_info:
        write_outputs(tmp_path, md, json_obj)

    # Not a raw OSError from the failed unlink -- the original RenderError.
    assert isinstance(exc_info.value, RenderError)
    assert isinstance(exc_info.value.__cause__, OSError)
    # Both cleanup targets left after the first `os.replace` failure (the
    # already-renamed md file, and the json tmp file) were attempted, even
    # though the first attempt raised.
    assert len(unlink_attempts) == 2


# --- Required Checks table cell escaping -------------------------------------------


def test_render_markdown_escapes_pipe_and_flattens_newline_in_check_notes() -> None:
    """`CheckResult.notes` is a captured subprocess output tail (`checks.py`'s
    `_tail_notes`, up to 30 lines) and can carry both a literal `|` and embedded
    newlines; either would otherwise break the markdown table row.
    """
    review = replace(
        _approve_review(),
        required_checks=[CheckResult(name='make check', status='fail', notes='line one|with pipe\nline two')],
    )

    md = render_markdown(review)

    rows = [line for line in md.splitlines() if line.startswith('| make check')]
    assert len(rows) == 1
    assert rows[0] == r'| make check | fail | line one\|with pipe line two |'
    assert '\n' not in rows[0]
