#!/usr/bin/env python3
"""Generate the agent-facing rule view and the decision/control registry.

Single source of truth is the decision markdown under ``governance/decisions/``.
Everything this script writes is derived and must never be hand-edited.

    build_views.py            rebuild governance/views/RULES.md + registry.json
    build_views.py --check    rebuild into memory, diff against disk, exit 1 on any
                              difference

Determinism is the contract. Two runs over the same decisions must produce
byte-identical output, or ``--check`` becomes a coin flip and the harness loses its
teeth quietly. No timestamps, no dict-order dependence, no locale-dependent sorting.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
DECISIONS_DIR = REPO_ROOT / 'governance' / 'decisions'
VIEWS_DIR = REPO_ROOT / 'governance' / 'views'
RULES_PATH = VIEWS_DIR / 'RULES.md'
REGISTRY_PATH = REPO_ROOT / 'governance' / 'registry.json'

GENERATED_HEADER = '<!-- GENERATED by governance/scripts/build_views.py. Do not edit. -->'

PREAMBLE = (
    'These rules are enforced by CI. Violating one fails the build. To change a rule you '
    'must supersede its decision — author a replacement, mark this one superseded, update '
    'the control and its pragma, and rebuild this view. Never edit code to evade a control.'
)

FRONTMATTER_RE = re.compile(r'\A---\n(?P<frontmatter>.*?)\n---\n(?P<body>.*)\Z', re.DOTALL)
SECTION_RE = re.compile(r'^##\s+(?P<title>.+?)\s*$', re.MULTILINE)
DECISION_ID_RE = re.compile(r'\ADEC-(?P<number>\d+)\Z')

STATUS_ACCEPTED = 'accepted'
ENFORCEMENT_BLOCK = 'block'


class DecisionError(Exception):
    """A decision file could not be parsed. Carries the path and the reason."""


@dataclass(frozen=True)
class Control:
    """One executable anchor listed in a decision's frontmatter."""

    decision: str
    path: str
    type: str
    enforcement: str
    pragma: str
    sha256: str | None

    def as_registry_entry(self) -> dict[str, Any]:
        return {
            'decision': self.decision,
            'enforcement': self.enforcement,
            'path': self.path,
            'pragma': self.pragma,
            'sha256': self.sha256,
            'type': self.type,
        }


@dataclass(frozen=True)
class Decision:
    """One decision file: its frontmatter, its rule text, and its controls."""

    id: str
    number: int
    title: str
    status: str
    kind: str
    created: str
    superseded_by: str | None
    rule: str
    controls: tuple[Control, ...]
    source: Path

    @property
    def is_live(self) -> bool:
        """Live means an agent should be shown this rule right now."""
        return self.status == STATUS_ACCEPTED and self.superseded_by is None

    @property
    def enforcement(self) -> str:
        """A decision blocks if any of its controls block. No controls means advisory."""
        if any(control.enforcement == ENFORCEMENT_BLOCK for control in self.controls):
            return ENFORCEMENT_BLOCK
        return 'warn'

    def as_registry_entry(self) -> dict[str, Any]:
        return {
            'id': self.id,
            'kind': self.kind,
            'status': self.status,
            'superseded_by': self.superseded_by,
            'title': self.title,
        }


def relative(path: Path) -> str:
    """Path relative to the repo root, or absolute if it lies outside it.

    Tests parse fixture decisions from a temp directory, so this must not assume
    every path it is handed is inside the tree.
    """
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _require(condition: bool, path: Path, message: str) -> None:
    if not condition:
        raise DecisionError(f'{relative(path)}: {message}')


def _normalise_optional(value: Any) -> str | None:
    """Treat YAML null, an empty string, and the literal 'null' as absent."""
    if value is None:
        return None
    text = str(value).strip()
    if text in ('', 'null', '~'):
        return None
    return text


def extract_section(body: str, title: str) -> str | None:
    """Return the text of a ``## <title>`` section, or None if it is absent."""
    for match in SECTION_RE.finditer(body):
        if match.group('title').strip().lower() != title.lower():
            continue
        start = match.end()
        following = SECTION_RE.search(body, start)
        end = following.start() if following else len(body)
        return body[start:end].strip()
    return None


def flatten(text: str) -> str:
    """Collapse a markdown block to one line so the view stays a flat list.

    Nothing is dropped — paragraphs are joined rather than truncated — because a rule
    silently losing half its text in the generated view is the exact failure this
    harness exists to prevent.
    """
    return ' '.join(text.split())


def parse_control(raw: Any, decision_id: str, path: Path) -> Control:
    _require(isinstance(raw, dict), path, f'{decision_id}: each entry under `controls` must be a mapping')
    _require('path' in raw, path, f'{decision_id}: a control is missing `path`')
    for field in ('type', 'enforcement', 'pragma'):
        _require(field in raw, path, f'{decision_id}: control `{raw["path"]}` is missing `{field}`')
    sha256 = _normalise_optional(raw.get('sha256'))
    if sha256 is not None:
        sha256 = sha256.lower()
    return Control(
        decision=decision_id,
        path=str(raw['path']).strip(),
        type=str(raw['type']).strip(),
        enforcement=str(raw['enforcement']).strip(),
        pragma=str(raw['pragma']).strip(),
        sha256=sha256,
    )


def parse_decision(path: Path) -> Decision:
    """Split a decision file into frontmatter and body, and pull out its rule."""
    text = path.read_text(encoding='utf-8')
    match = FRONTMATTER_RE.match(text)
    _require(match is not None, path, 'missing YAML frontmatter delimited by `---` lines')
    assert match is not None  # narrowed by _require; keeps type checkers honest

    try:
        frontmatter = yaml.safe_load(match.group('frontmatter'))
    except yaml.YAMLError as exc:
        raise DecisionError(f'{relative(path)}: frontmatter is not valid YAML: {exc}') from exc
    _require(isinstance(frontmatter, dict), path, 'frontmatter must be a YAML mapping')

    for field in ('id', 'title', 'status', 'kind'):
        _require(field in frontmatter, path, f'frontmatter is missing `{field}`')

    decision_id = str(frontmatter['id']).strip()
    id_match = DECISION_ID_RE.match(decision_id)
    _require(id_match is not None, path, f'`id` must look like DEC-<number>, got {decision_id!r}')
    assert id_match is not None

    rule = extract_section(match.group('body'), 'Rule')
    _require(rule is not None and rule.strip() != '', path, f'{decision_id}: no `## Rule` section, or it is empty')
    assert rule is not None

    raw_controls = frontmatter.get('controls') or []
    _require(isinstance(raw_controls, list), path, f'{decision_id}: `controls` must be a list')
    controls = tuple(parse_control(entry, decision_id, path) for entry in raw_controls)

    return Decision(
        id=decision_id,
        number=int(id_match.group('number')),
        title=str(frontmatter['title']).strip(),
        status=str(frontmatter['status']).strip(),
        kind=str(frontmatter['kind']).strip(),
        created=str(_normalise_optional(frontmatter.get('created')) or ''),
        superseded_by=_normalise_optional(frontmatter.get('superseded_by')),
        rule=flatten(rule),
        controls=controls,
        source=path,
    )


def load_decisions(decisions_dir: Path | None = None) -> list[Decision]:
    """Parse every decision file, sorted by numeric id so output is deterministic.

    ``decisions_dir`` resolves at call time rather than as a default argument, so the
    module constant can be repointed at a temp tree for testing.
    """
    paths = sorted((decisions_dir or DECISIONS_DIR).glob('DEC-*.md'))
    decisions = [parse_decision(path) for path in paths]
    return sorted(decisions, key=lambda decision: (decision.number, decision.id))


def render_rules(decisions: list[Decision]) -> str:
    """Render the agent-facing view: live rules only, one imperative line each."""
    lines = [
        GENERATED_HEADER,
        '',
        '# Binding rules for agents working in this repo',
        '',
        PREAMBLE,
        '',
    ]
    live = [decision for decision in decisions if decision.is_live]
    if live:
        lines.extend(f'- **[{decision.id}] {decision.rule}** ({decision.enforcement})' for decision in live)
    else:
        lines.append('_No rules are currently in force._')
    lines.append('')
    return '\n'.join(lines)


def render_registry(decisions: list[Decision]) -> str:
    """Render the flat index of every decision and every control, live or not."""
    controls = [control for decision in decisions for control in decision.controls]
    payload = {
        'controls': sorted(
            (control.as_registry_entry() for control in controls),
            key=lambda entry: (entry['path'], entry['decision']),
        ),
        'decisions': [decision.as_registry_entry() for decision in decisions],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + '\n'


def build(decisions_dir: Path | None = None) -> dict[Path, str]:
    """Return the full generated output, keyed by the path each artifact belongs at."""
    decisions = load_decisions(decisions_dir)
    return {RULES_PATH: render_rules(decisions), REGISTRY_PATH: render_registry(decisions)}


def write(artifacts: dict[Path, str]) -> None:
    for path, content in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding='utf-8')
        print(f'wrote {path.relative_to(REPO_ROOT).as_posix()}')


def check(artifacts: dict[Path, str]) -> int:
    """Diff the freshly built output against disk. Returns a process exit code."""
    stale = False
    for path, expected in artifacts.items():
        relative = path.relative_to(REPO_ROOT).as_posix()
        actual = path.read_text(encoding='utf-8') if path.exists() else ''
        if actual == expected:
            continue
        stale = True
        reason = 'missing — never generated' if not path.exists() else 'differs from a fresh build'
        print(f'FAIL {relative}: {reason}', file=sys.stderr)
        diff = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f'{relative} (on disk)',
            tofile=f'{relative} (freshly built)',
        )
        sys.stderr.writelines(diff)
        print(file=sys.stderr)
    if stale:
        print(
            'Generated files are out of date or were hand-edited. Run `make views` and '
            'commit the result. Never hand-edit anything under governance/views/ or '
            'governance/registry.json — they are derived from governance/decisions/.',
            file=sys.stderr,
        )
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        '--check',
        action='store_true',
        help='do not write; rebuild into memory and fail if the files on disk differ',
    )
    args = parser.parse_args(argv)

    try:
        artifacts = build()
    except DecisionError as exc:
        print(f'FAIL {exc}', file=sys.stderr)
        return 1

    if args.check:
        return check(artifacts)
    write(artifacts)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
